# Generated by Django 4.1.3 on 2023-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m777", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("cat_image", models.ImageField(upload_to="upload/category/")),
            ],
        ),
    ]
