# Generated by Django 4.1.3 on 2023-04-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("m777", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("desc", models.TextField(max_length=200)),
                ("pro_image", models.ImageField(upload_to="upload/category/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="m777.category"
                    ),
                ),
            ],
        ),
    ]
