# Generated by Django 4.1.3 on 2023-04-06 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m777", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="start",
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 6, 23, 49, 38, 455701)
            ),
        ),
    ]
